server {
    listen 80;
    server_name www.smarttydigital.com.br;
    return 301 https://smarttydigital.com.br$request_uri;
}

server {
    listen 80 default_server;
    server_name smarttydigital.com.br _;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
}
